In [138]:
import pandas as pd

In [139]:
df=pd.read_csv("2023_Countries by Population.csv")
df

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.514994e+09,1.670491e+09,India,3287590.00,2973190.00,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.415606e+09,1.312636e+09,China,9706961.00,9424702.90,CN,CHN,-0.0113,-0.0002,0.1781,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.521623e+08,3.753920e+08,United States,9372610.00,9147420.00,US,USA,0.0581,0.0050,0.0425,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.00,1877519.00,ID,IDN,0.0727,0.0074,0.0347,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.740298e+08,3.678085e+08,Pakistan,881912.00,770880.00,PK,PAK,0.1495,0.0198,0.0300,311.9625,807.9829,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,500,11452.0,5.138000e+03,4.938000e+03,4.390000e+03,4.386000e+03,4.301000e+03,3.781000e+03,Montserrat,102.00,102.00,MS,MSR,NaN,-0.0009,NaN,43.0000,111.3700,230
230,238,2240.0,3.080000e+03,3.187000e+03,3.780000e+03,3.791000e+03,3.869000e+03,3.779000e+03,Falkland Islands,12173.00,12173.00,FK,FLK,NaN,0.0029,NaN,0.3114,0.8066,231
231,570,3637.0,2.074000e+03,1.812000e+03,1.934000e+03,1.935000e+03,1.948000e+03,2.096000e+03,Niue,261.00,261.00,NU,NIU,0.0000,0.0005,NaN,7.4138,19.2017,232
232,772,1647.0,1.666000e+03,1.367000e+03,1.871000e+03,1.893000e+03,2.046000e+03,2.430000e+03,Tokelau,12.00,10.00,TK,TKL,NaN,0.0118,NaN,189.3000,490.2870,233
233,336,733.0,6.510000e+02,5.960000e+02,5.100000e+02,5.180000e+02,5.610000e+02,7.310000e+02,Vatican City,0.44,0.44,VA,VAT,NaN,0.0157,NaN,1177.2727,3049.1364,234

In [140]:
df.isnull().sum()

place              0
pop1980            0
pop2000            0
pop2010            0
pop2022            0
pop2023            0
pop2030            0
pop2050            0
country            0
area               0
landAreaKm         0
cca2               1
cca3               0
netChange          8
growthRate         0
worldPercentage    6
density            0
densityMi          0
rank               0
dtype: int64

In [141]:
df[df.loc[:,'worldPercentage'].isnull()].index

Index([228, 229, 230, 231, 232, 233], dtype='int64')

In [142]:
one=df.loc[:,'pop2023']*df.loc[:,'growthRate']
inctwo=one*2
inctwo

0      2.314377e+07
1     -5.702685e+05
2      3.399966e+06
3      4.107505e+06
4      9.523232e+06
           ...
229   -7.894800e+00
230    2.198780e+01
231    1.935000e+00
232    4.467480e+01
233    1.626520e+01
Length: 234, dtype: float64

In [143]:
df.loc[:,'pop2023']+inctwo

0      1.451771e+09
1      1.425101e+09
2      3.433965e+08
3      2.816416e+08
4      2.500089e+08
           ...
229    4.378105e+03
230    3.812988e+03
231    1.936935e+03
232    1.937675e+03
233    5.342652e+02
Length: 234, dtype: float64

In [144]:
# df.loc[:,'pop2025']=df.loc[:,'pop2023']+inctwo
# df

In [145]:
# df.drop('pop2025',axis=1,inplace=True)

In [146]:
# df.insert(loc=6,column='pop2025', value=df.loc[:,'pop2023']+inctwo)
df

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.514994e+09,1.670491e+09,India,3287590.00,2973190.00,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.415606e+09,1.312636e+09,China,9706961.00,9424702.90,CN,CHN,-0.0113,-0.0002,0.1781,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.521623e+08,3.753920e+08,United States,9372610.00,9147420.00,US,USA,0.0581,0.0050,0.0425,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.00,1877519.00,ID,IDN,0.0727,0.0074,0.0347,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.740298e+08,3.678085e+08,Pakistan,881912.00,770880.00,PK,PAK,0.1495,0.0198,0.0300,311.9625,807.9829,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,500,11452.0,5.138000e+03,4.938000e+03,4.390000e+03,4.386000e+03,4.301000e+03,3.781000e+03,Montserrat,102.00,102.00,MS,MSR,NaN,-0.0009,NaN,43.0000,111.3700,230
230,238,2240.0,3.080000e+03,3.187000e+03,3.780000e+03,3.791000e+03,3.869000e+03,3.779000e+03,Falkland Islands,12173.00,12173.00,FK,FLK,NaN,0.0029,NaN,0.3114,0.8066,231
231,570,3637.0,2.074000e+03,1.812000e+03,1.934000e+03,1.935000e+03,1.948000e+03,2.096000e+03,Niue,261.00,261.00,NU,NIU,0.0000,0.0005,NaN,7.4138,19.2017,232
232,772,1647.0,1.666000e+03,1.367000e+03,1.871000e+03,1.893000e+03,2.046000e+03,2.430000e+03,Tokelau,12.00,10.00,TK,TKL,NaN,0.0118,NaN,189.3000,490.2870,233
233,336,733.0,6.510000e+02,5.960000e+02,5.100000e+02,5.180000e+02,5.610000e+02,7.310000e+02,Vatican City,0.44,0.44,VA,VAT,NaN,0.0157,NaN,1177.2727,3049.1364,234

In [147]:
df[df.loc[:,"cca2"].isnull()].index

Index([144], dtype='int64')

In [148]:
df

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.514994e+09,1.670491e+09,India,3287590.00,2973190.00,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.415606e+09,1.312636e+09,China,9706961.00,9424702.90,CN,CHN,-0.0113,-0.0002,0.1781,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.521623e+08,3.753920e+08,United States,9372610.00,9147420.00,US,USA,0.0581,0.0050,0.0425,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.00,1877519.00,ID,IDN,0.0727,0.0074,0.0347,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.740298e+08,3.678085e+08,Pakistan,881912.00,770880.00,PK,PAK,0.1495,0.0198,0.0300,311.9625,807.9829,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,500,11452.0,5.138000e+03,4.938000e+03,4.390000e+03,4.386000e+03,4.301000e+03,3.781000e+03,Montserrat,102.00,102.00,MS,MSR,NaN,-0.0009,NaN,43.0000,111.3700,230
230,238,2240.0,3.080000e+03,3.187000e+03,3.780000e+03,3.791000e+03,3.869000e+03,3.779000e+03,Falkland Islands,12173.00,12173.00,FK,FLK,NaN,0.0029,NaN,0.3114,0.8066,231
231,570,3637.0,2.074000e+03,1.812000e+03,1.934000e+03,1.935000e+03,1.948000e+03,2.096000e+03,Niue,261.00,261.00,NU,NIU,0.0000,0.0005,NaN,7.4138,19.2017,232
232,772,1647.0,1.666000e+03,1.367000e+03,1.871000e+03,1.893000e+03,2.046000e+03,2.430000e+03,Tokelau,12.00,10.00,TK,TKL,NaN,0.0118,NaN,189.3000,490.2870,233
233,336,733.0,6.510000e+02,5.960000e+02,5.100000e+02,5.180000e+02,5.610000e+02,7.310000e+02,Vatican City,0.44,0.44,VA,VAT,NaN,0.0157,NaN,1177.2727,3049.1364,234

In [149]:
df.loc[144,['country']]

country    Namibia
Name: 144, dtype: object

In [150]:
df.loc[144,['cca2']]='NB'

In [151]:
df.loc[144,['cca2']]

cca2    NB
Name: 144, dtype: object

In [152]:
df.isnull().sum()

place              0
pop1980            0
pop2000            0
pop2010            0
pop2022            0
pop2023            0
pop2030            0
pop2050            0
country            0
area               0
landAreaKm         0
cca2               0
cca3               0
netChange          8
growthRate         0
worldPercentage    6
density            0
densityMi          0
rank               0
dtype: int64

In [153]:
[]
[]

[]

In [154]:
df.loc[[228,229,230, 231, 232, 233],['country']]

                       country
228  Saint Pierre and Miquelon
229                 Montserrat
230           Falkland Islands
231                       Niue
232                    Tokelau
233               Vatican City

In [155]:
total2023=df.loc[:,'pop2023'].sum()

In [156]:
sai=df.loc[228,'pop2023']/total2023
df.loc[228,'worldPercentage']=sai

In [159]:
nullin=df[df.loc[:,'worldPercentage'].isnull()].index

In [163]:
wor = df.loc[nullin,'pop2023']/total2023
df.loc[nullin,'worldPercentage']=wor

In [164]:
df.isnull().sum()

place              0
pop1980            0
pop2000            0
pop2010            0
pop2022            0
pop2023            0
pop2030            0
pop2050            0
country            0
area               0
landAreaKm         0
cca2               0
cca3               0
netChange          8
growthRate         0
worldPercentage    0
density            0
densityMi          0
rank               0
dtype: int64

In [165]:
df.head(20)

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.514994e+09,1.670491e+09,India,3287590.0,2973190.0,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1
1,156,982372466.0,1.264099e+09,1.348191e+09,1.425887e+09,1.425671e+09,1.415606e+09,1.312636e+09,China,9706961.0,9424702.9,CN,CHN,-0.0113,-0.0002,0.1781,151.2696,391.7884,2
2,840,223140018.0,2.823986e+08,3.111828e+08,3.382899e+08,3.399966e+08,3.521623e+08,3.753920e+08,United States,9372610.0,9147420.0,US,USA,0.0581,0.0050,0.0425,37.1686,96.2666,3
3,360,148177096.0,2.140724e+08,2.440162e+08,2.755013e+08,2.775341e+08,2.921501e+08,3.172252e+08,Indonesia,1904569.0,1877519.0,ID,IDN,0.0727,0.0074,0.0347,147.8196,382.8528,4
4,586,80624057.0,1.543699e+08,1.944545e+08,2.358249e+08,2.404857e+08,2.740298e+08,3.678085e+08,Pakistan,881912.0,770880.0,PK,PAK,0.1495,0.0198,0.0300,311.9625,807.9829,5
5,566,72951439.0,1.228520e+08,1.609529e+08,2.185412e+08,2.238046e+08,2.625804e+08,3.774599e+08,Nigeria,923768.0,910770.0,NG,NGA,0.1680,0.0241,0.0280,245.7312,636.4439,6
6,76,122288383.0,1.758737e+08,1.963535e+08,2.153135e+08,2.164224e+08,2.239090e+08,2.308857e+08,Brazil,8515767.0,8358140.0,BR,BRA,0.0393,0.0052,0.0270,25.8936,67.0645,7
7,50,83929765.0,1.291933e+08,1.483911e+08,1.711864e+08,1.729543e+08,1.844241e+08,2.039049e+08,Bangladesh,147570.0,130170.0,BD,BGD,0.0557,0.0103,0.0216,1328.6803,3441.2821,8
8,643,138257420.0,1.468448e+08,1.432426e+08,1.447133e+08,1.444444e+08,1.414327e+08,1.331330e+08,Russia,17098242.0,16376870.0,RU,RUS,-0.0158,-0.0019,0.0180,8.8200,22.8439,9
9,484,67705186.0,9.787344e+07,1.125324e+08,1.275041e+08,1.284556e+08,1.345341e+08,1.437724e+08,Mexico,1964375.0,1943950.0,MX,MEX,0.0299,0.0075,0.0160,66.0797,171.1463,10
10,231,34945469.0,6.703187e+07,8.923779e+07,1.233799e+08,1.265271e+08,1.492964e+08,2.148123e+08,Ethiopia,1104300.0,1128571.3,ET,ETH,0.1008,0.0255,0.0158,112.1126,290.3716,11
11,392,117624196.0,1.268039e+08,1.281054e+08,1.239517e+08,1.232945e+08,1.185148e+08,1.037844e+08,Japan,377930.0,364500.0,JP,JPN,-0.0209,-0.0053,0.0154,338.2566,876.0845,12
12,608,48419546.0,7.795822e+07,9.463670e+07,1.155590e+08,1.173374e+08,1.294533e+08,1.578916e+08,Philippines,342353.0,298170.0,PH,PHL,0.0561,0.0154,0.0147,393.5251,1019.2299,13
13,818,43748556.0,7.137137e+07,8.725241e+07,1.109901e+08,1.127166e+08,1.251517e+08,1.603399e+08,Egypt,1002450.0,995450.0,EG,EGY,0.0551,0.0156,0.0141,113.2318,293.2704,14
14,180,26708686.0,4.861632e+07,6.639126e+07,9.901021e+07,1.022628e+08,1.275821e+08,2.174940e+08,DR Congo,2344858.0,2267050.0,CD,COD,0.1050,0.0329,0.0128,45.1083,116.8305,15
15,704,52968270.0,7.900114e+07,8.741101e+07,9.818686e+07,9.885895e+07,1.026999e+08,1.070129e+08,Vietnam,331212.0,313429.0,VN,VNM,0.0208,0.0068,0.0123,315.4110,816.9145,16
16,364,38520664.0,6.554438e+07,7.537386e+07,8.855057e+07,8.917277e+07,9.292102e+07,9.900720e+07,Iran,1648195.0,1622500.0,IR,IRN,0.0208,0.0070,0.0111,54.9601,142.3467,17
17,792,44089069.0,6.411355e+07,7.319534e+07,8.534124e+07,8.581620e+07,8.887970e+07,9.582926e+07,Turkey,783562.0,783562.0,TR,TUR,0.0143,0.0056,0.0107,109.5206,283.6584,18
18,276,77786703.0,8.155168e+07,8.132509e+07,8.336984e+07,8.329463e+07,8.276268e+07,7.893223e+07,Germany,357114.0,349390.0,DE,DEU,-0.0012,-0.0009,0.0104,238.4002,617.4564,19
19,764,45737753.0,6.306660e+07,6.827049e+07,7.169703e+07,7.180128e+07,7.206002e+07,6.788008e+07,Thailand,513120.0,510890.0,TH,THA,0.0030,0.0015,0.0090,140.5416,364.0026,20

In [ ]:
# df.loc[1,['pop1980','pop2000',"pop2010","pop2022","pop2023"]].mean()

np.float64(1289244318.4)

In [189]:
df.loc[0,'pop2030']-df.loc[0,'pop2023']

np.float64(86366417.0)

In [190]:
df[df["country"]=='India']

,place,pop1980,pop2000,pop2010,pop2022,pop2023,pop2030,pop2050,country,area,landAreaKm,cca2,cca3,netChange,growthRate,worldPercentage,density,densityMi,rank
0,356,696828385.0,1.059634e+09,1.240614e+09,1.417173e+09,1.428628e+09,1.514994e+09,1.670491e+09,India,3287590.0,2973190.0,IN,IND,0.4184,0.0081,0.1785,480.5033,1244.5036,1

In [1]:
import pandas as pd

# Base district list (official dataset from DataMeet)
url = "https://raw.githubusercontent.com/datameet/india-districts/master/data/districts.csv"
df = pd.read_csv(url)

# Normalize column names
df = df.rename(columns={"state": "State", "district": "District"})

# ---- Earthquake Risk ----
high_eq_states = [
    "Himachal Pradesh","Uttarakhand","Jammu and Kashmir","Ladakh","Assam",
    "Arunachal Pradesh","Manipur","Mizoram","Nagaland","Tripura","Meghalaya",
    "Bihar","Gujarat","Delhi","Sikkim"
]

def earthquake_risk(state):
    if state in high_eq_states:
        return "Very High"
    elif state in ["Maharashtra","Punjab","Haryana","West Bengal","Rajasthan"]:
        return "High"
    elif state in ["Tamil Nadu","Karnataka","Andhra Pradesh","Telangana","Odisha"]:
        return "Moderate"
    else:
        return "Low"

# ---- Flood Risk ----
flood_high_states = [
    "Assam","Bihar","Uttar Pradesh","West Bengal","Odisha","Kerala","Jharkhand"
]

def flood_risk(state):
    if state in flood_high_states:
        return "Very High"
    elif state in ["Punjab","Haryana","Gujarat","Maharashtra","Andhra Pradesh","Tamil Nadu"]:
        return "High"
    elif state in ["Karnataka","Chhattisgarh","Madhya Pradesh"]:
        return "Moderate"
    else:
        return "Low"

# ---- Cyclone Risk ----
cyclone_very_high = ["Odisha","Andhra Pradesh","West Bengal","Tamil Nadu"]
cyclone_high = ["Gujarat","Maharashtra","Kerala","Karnataka","Goa"]

def cyclone_risk(state):
    if state in cyclone_very_high:
        return "Very High"
    elif state in cyclone_high:
        return "High"
    elif state in ["Telangana","Chhattisgarh"]:
        return "Moderate"
    else:
        return "Low"

# Apply rules
df["Earthquake_Risk"] = df["State"].apply(earthquake_risk)
df["Flood_Risk"] = df["State"].apply(flood_risk)
df["Cyclone_Risk"] = df["State"].apply(cyclone_risk)

# Save to CSV
df[["State","District","Earthquake_Risk","Flood_Risk","Cyclone_Risk"]].to_csv(
    "India_All_Districts_Disaster_Risk.csv", index=False
)

print("✅ CSV generated: India_All_Districts_Disaster_Risk.csv")

HTTPError: HTTP Error 404: Not Found