In [37]:
import pandas as pd
import numpy as np

In [38]:
df=pd.read_csv("cleaned_data.csv")

In [39]:
osx=df[df["os"].isna()].index

In [40]:
os=df["os"].mode()
df.loc[osx,"os"]= "Android v12"

In [41]:
battery=df["battery_mah"].mode()
bat=df[df["battery_mah"].isna()].index
df.loc[bat,"battery_mah"]=battery

In [42]:
df.drop(columns="clock_ghz",axis=1,inplace=True)
df.drop(columns="memory_card_max_gb",axis=1,inplace=True)
df.drop(columns="memory_card_supported",axis=1,inplace=True)
df.drop(columns="memory_card_type",axis=1,inplace=True)
df.drop(columns="VoLTE",axis=1,inplace=True)
df.drop(columns="refresh_rate_hz",axis=1,inplace=True)
df.drop(columns="sim_type",axis=1,inplace=True)
df.drop(columns="display_type",axis=1,inplace=True)

In [44]:
df

,model,price,rating,os,network_type,NFC,ir_blaster,chipset,core_type,ram_gb,storage_gb,battery_mah,fast_charge_w,screen_size_in,resolution,rear_camera_mp_list,rear_camera_count,rear_camera_max_mp,front_camera_mp
0,oneplus 11 5g,54999,89.0,Android v13,5g,True,False,Snapdragon 8 Gen2,Octa Core,12,12,5000.0,100.0,6.70,1440x3216,"[50, 48, 32]",3,50.0,16.0
1,oneplus nord ce 2 lite 5g,19989,81.0,Android v12,5g,False,False,Snapdragon 695,Octa Core,6,6,5000.0,33.0,6.59,1080x2412,"[64, 2, 2]",3,64.0,16.0
2,samsung galaxy a14 5g,16499,75.0,Android v13,5g,False,False,Exynos 1330,Octa Core,4,4,5000.0,15.0,6.60,1080x2408,"[50, 2, 2]",3,50.0,13.0
3,motorola moto g62 5g,14999,81.0,Android v12,5g,False,False,Snapdragon 695,Octa Core,6,6,5000.0,NaN,6.55,1080x2400,"[50, 8, 2]",3,50.0,16.0
4,realme 10 pro plus,24999,82.0,Android v13,5g,False,False,Dimensity 1080,Octa Core,6,6,5000.0,67.0,6.70,1080x2412,"[108, 8, 2]",3,108.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,motorola moto edge s30 pro,34990,83.0,Android v12,5g,False,False,Snapdragon 8 Gen1,Octa Core,8,8,5000.0,68.2,6.67,1080x2460,"[64, 8, 2]",3,64.0,16.0
964,honor x8 5g,14990,75.0,Android v11,5g,False,False,Snapdragon 480+,Octa Core,6,6,5000.0,22.5,6.50,720x1600,"[48, 2]",2,48.0,8.0
965,poco x4 gt 5g,28990,85.0,Android v12,5g,True,True,Dimensity 8100,Octa Core,8,8,5080.0,67.0,6.60,1080x2460,"[64, 8, 2]",3,64.0,16.0
966,motorola moto g91 5g,19990,80.0,Android v12,5g,True,False,Snapdragon 695,Octa Core,6,6,5000.0,NaN,6.80,1080x2400,"[108, 8, 2]",3,108.0,32.0
967,samsung galaxy m52s 5g,24990,74.0,Android v12,5g,False,False,Octa Core Processor,Octa Core,8,8,5000.0,NaN,6.50,1080x2400,"[64, 8, 5]",3,64.0,32.0

In [45]:
df.isna().sum()

model                    0
price                    0
rating                   0
os                       0
network_type             0
NFC                      0
ir_blaster               0
chipset                  0
core_type                6
ram_gb                   0
storage_gb               0
battery_mah             11
fast_charge_w          204
screen_size_in           1
resolution               1
rear_camera_mp_list      0
rear_camera_count        0
rear_camera_max_mp      16
front_camera_mp         25
dtype: int64

In [50]:
core=df[df["core_type"].isna()].index
df.head(30)

,model,price,rating,os,network_type,NFC,ir_blaster,chipset,core_type,ram_gb,storage_gb,battery_mah,fast_charge_w,screen_size_in,resolution,rear_camera_mp_list,rear_camera_count,rear_camera_max_mp,front_camera_mp
0,oneplus 11 5g,54999,89.0,Android v13,5g,True,False,Snapdragon 8 Gen2,Octa Core,12,12,5000.0,100.0,6.70,1440x3216,"[50, 48, 32]",3,50.0,16.0
1,oneplus nord ce 2 lite 5g,19989,81.0,Android v12,5g,False,False,Snapdragon 695,Octa Core,6,6,5000.0,33.0,6.59,1080x2412,"[64, 2, 2]",3,64.0,16.0
2,samsung galaxy a14 5g,16499,75.0,Android v13,5g,False,False,Exynos 1330,Octa Core,4,4,5000.0,15.0,6.60,1080x2408,"[50, 2, 2]",3,50.0,13.0
3,motorola moto g62 5g,14999,81.0,Android v12,5g,False,False,Snapdragon 695,Octa Core,6,6,5000.0,NaN,6.55,1080x2400,"[50, 8, 2]",3,50.0,16.0
4,realme 10 pro plus,24999,82.0,Android v13,5g,False,False,Dimensity 1080,Octa Core,6,6,5000.0,67.0,6.70,1080x2412,"[108, 8, 2]",3,108.0,16.0
5,samsung galaxy f23 5g,16999,80.0,Android v12,5g,True,False,Snapdragon 750G,Octa Core,6,6,5000.0,25.0,6.60,1080x2408,"[50, 8, 2]",3,50.0,8.0
6,apple iphone 14,65999,81.0,iOS v16,5g,True,False,Bionic A15,Hexa Core,6,6,3279.0,NaN,6.10,1170x2532,"[12, 12]",2,12.0,12.0
7,xiaomi redmi note 12 pro plus,29999,86.0,Android v12,5g,False,True,Dimensity 1080,Octa Core,8,8,4980.0,120.0,6.67,1080x2400,"[200, 8, 2]",3,200.0,16.0
8,nothing phone 1,26749,85.0,Android v12,5g,True,False,Snapdragon 778G Plus,Octa Core,8,8,4500.0,33.0,6.55,1080x2400,"[50, 50]",2,50.0,16.0
9,oneplus nord 2t 5g,28999,84.0,Android v12,5g,True,False,Dimensity 1300,Octa Core,8,8,4500.0,80.0,6.43,1080x2400,"[50, 8, 2]",3,50.0,32.0
10,realme 10 pro,18999,82.0,Android v13,5g,False,False,Snapdragon 695,Octa Core,6,6,5000.0,33.0,6.72,1080x2400,"[108, 2]",2,108.0,16.0
11,oppo a78,18999,79.0,Android v12,5g,True,False,Dimensity 700 5G,Octa Core,8,8,5000.0,33.0,6.56,720x1612,"[50, 2]",2,50.0,8.0
12,xiaomi redmi note 12 pro 5g,24762,79.0,Android v12,5g,False,True,Dimensity 1080,Octa Core,6,6,5000.0,67.0,6.67,1080x2400,"[50, 8, 2]",3,50.0,16.0
13,vivo t1 5g,16990,80.0,Android v12,5g,False,False,Snapdragon 695,Octa Core,6,6,5000.0,18.0,6.58,1080x2408,"[50, 2, 2]",3,50.0,16.0
14,samsung galaxy s23 ultra 5g,114990,80.0,Android v13,5g,True,False,Snapdragon 8 Gen2,Octa Core,8,8,5000.0,45.0,6.80,1440x3088,[200],1,200.0,12.0
15,apple iphone 13,62999,79.0,iOS v15,5g,True,False,Bionic A15,Hexa Core,4,4,3240.0,NaN,6.10,1170x2532,"[12, 12]",2,12.0,12.0
16,vivo y16,9999,65.0,Android v12,4g,False,False,Helio P35,Octa Core,3,3,5000.0,10.0,6.51,720x1600,"[13, 2]",2,13.0,5.0
17,oppo reno 9 pro plus,45999,86.0,Android v13,5g,True,False,Snapdragon 8+ Gen1,Octa Core,16,16,4700.0,80.0,6.70,1080x2412,"[50, 8, 2]",3,50.0,32.0
18,oneplus 10r 5g,32999,86.0,Android v12,5g,True,False,Dimensity 8100 Max,Octa Core,8,8,5000.0,80.0,6.70,1080x2412,"[50, 8, 2]",3,50.0,16.0
19,vivo y22,14499,72.0,Android v12,4g,False,False,Helio G70,Octa Core,4,4,5000.0,18.0,6.55,720x1612,"[50, 2]",2,50.0,8.0
20,oneplus 11r,39999,85.0,Android v13,5g,True,False,Snapdragon 8+ Gen1,Octa Core,8,8,5000.0,100.0,6.70,1080x2412,"[50, 12, 2]",3,50.0,16.0
21,vivo v25 pro 5g,35999,85.0,Android v12,5g,False,False,Dimensity 1300,Octa Core,8,8,4830.0,66.0,6.56,1080x2376,"[64, 8, 2]",3,64.0,32.0
22,poco x4 pro 5g,14999,80.0,Android v11,5g,False,True,Snapdragon 695,Octa Core,6,6,5000.0,67.0,6.67,1080x2400,"[64, 8, 2]",3,64.0,16.0
23,xiaomi redmi note 12,17859,76.0,Android v12,5g,False,True,Snapdragon 4 Gen 1,Octa Core,4,4,5000.0,33.0,6.67,1080x2400,"[48, 8, 2]",3,48.0,13.0
24,vivo v26 pro,42990,87.0,Android v13,5g,True,False,Dimensity 9000 Plus,Octa Core,12,12,4800.0,100.0,6.70,1080x2400,"[64, 8, 2]",3,64.0,32.0
25,samsung galaxy s20 fe 5g,31239,88.0,Android v10,5g,True,False,Snapdragon 865,Octa Core,8,8,4500.0,NaN,6.50,1080x2400,"[12, 12, 8]",3,12.0,32.0
26,oneplus nord ce 2 lite 5g,21995,84.0,Android v12,5g,False,False,Snapdragon 695,Octa Core,8,8,5000.0,33.0,6.59,1080x2412,"[64, 2, 2]",3,64.0,16.0
27,apple iphone 14 pro max,129990,76.0,iOS v16,5g,True,False,Bionic A16,Hexa Core,6,6,4323.0,NaN,6.70,1290x2796,"[48, 12, 12]",3,48.0,12.0
28,vivo v25 5g,27999,83.0,Android v12,5g,False,False,Dimensity 900,Octa Core,8,8,4500.0,44.0,6.44,1080x2408,"[64, 8, 2]",3,64.0,50.0
29,oneplus 11 pro,69999,80.0,Android v13,5g,True,False,Snapdragon 8 Gen2,Octa Core,8,8,4500.0,100.0,6.70,1440x3216,"[50, 48, 32]",3,50.0,16.0

In [51]:
df.loc[core,:]

,model,price,rating,os,network_type,NFC,ir_blaster,chipset,core_type,ram_gb,storage_gb,battery_mah,fast_charge_w,screen_size_in,resolution,rear_camera_mp_list,rear_camera_count,rear_camera_max_mp,front_camera_mp
152,apple iphone 15 pro max,142990,79.0,iOS v15,5g,True,False,Bionic A16,NaN,8,8,4352.0,25.0,6.68,1284x2778,"[50, 12, 12]",3,50.0,12.0
262,apple iphone xr2,71999,60.0,iOS v12.3,4g,True,False,Apple A13,NaN,4,4,3060.0,NaN,6.10,828x1792,"[12, 5]",2,12.0,7.0
280,apple iphone 14 mini,69990,70.0,iOS v15,4g,True,False,Bionic A16,NaN,6,6,3500.0,NaN,5.42,1080x2340,"[12, 12]",2,12.0,12.0
426,nokia x50 5g,34999,76.0,Android v11,5g,False,False,Snapdragon 775,NaN,6,6,6000.0,33.0,6.81,1080x2400,[108],1,108.0,32.0
445,apple iphone 15 pro,130990,75.0,iOS v15,5g,True,False,Bionic A16,NaN,8,8,NaN,NaN,6.06,1170x2532,"[50, 12, 12]",3,50.0,12.0
705,apple iphone 15,82990,72.0,iOS v15,4g,True,False,Bionic A16,NaN,6,6,3285.0,NaN,6.06,1170x2532,"[50, 13]",2,50.0,13.0