In [39]:
import pandas as pd 
import numpy as np

In [40]:
df=pd.read_csv("neet_data.csv")

In [41]:
df

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [42]:
df["retweet_count"].sort_values(ascending=False)

32860    614304
33262    581097
35111    381458
32585    204348
38044    192350
          ...
47347         0
47348         0
47349         0
47351         0
47332         0
Name: retweet_count, Length: 47381, dtype: int64

In [43]:
top10=df["retweet_count"].sort_values(ascending=False).head(10).index

In [44]:
df.loc[32860,["source","user_name","user_url","created_at","retweet_count","tweet","user_follower_count"]]

source                                                Twitter for iPhone
user_name                           \xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3
user_url                                         https://t.co/cHZdP4uOdu
created_at                                           2020-11-08 05:30:01
retweet_count                                                     614304
tweet                  RT @JoeBiden: America, I\xe2\x80\x99m honored ...
user_follower_count                                                   62
Name: 32860, dtype: object

In [45]:
df.loc[top10,"retweet_count"].sum()
"THE TOP 10 RETWEET SUM IS 2652225"

'THE TOP 10 RETWEET SUM IS 2652225'

In [46]:
an=df[df["source"]=="Twitter for Android"].index
df.loc[an,'retweet_count'].sum()
'SUM OF ALL DONE BY TWITTER FOR ANDROID IS 9386742'

'SUM OF ALL DONE BY TWITTER FOR ANDROID IS 9386742'

In [47]:
df["user_follower_count"].max()
df[df.loc[:,"user_follower_count"]==13934355]

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
44355,2020-11-01 10:49:41,15,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,#Watch | Farmer's son Anil Kumar secures 77th ...,123
44367,2020-11-01 10:45:04,24,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,"#Watch | In his 9th attempt, Arvind Kumar crac...",136
44424,2020-11-01 10:01:49,11,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,"Watch | ""My coaching centre supported me both ...",140
44436,2020-11-01 09:57:24,14,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,"Watch | ""My father is a farmer and my mother i...",133

In [48]:
df.loc[44367,["user_name","user_location"]]

user_name         NDTV
user_location    India
Name: 44367, dtype: object

In [49]:
val=df["user_follower_count"]/df['user_friends_count']

In [50]:
df["follower_friend_ratio"]=val

In [51]:
df.isnull().sum()

created_at                   0
retweet_count                0
source                      19
user_id                      0
user_name                    1
user_description         10871
user_follower_count          0
user_friends_count           0
user_location            21134
user_verified                0
user_url                 38101
tweet                        0
length_of_tweet              0
follower_friend_ratio      147
dtype: int64

In [52]:
nain=df[df["user_description"].isnull()].index
df.loc[nain,'user_description']="Twitter user"

In [53]:
df.drop(["source","user_name","user_location","user_url","follower_friend_ratio"],axis=1,inplace=True)

In [54]:
df.insert(loc=2,column="is_allow",value=None)

In [55]:
# df.drop("tweet",axis=1,inplace=True)
df

,created_at,retweet_count,is_allow,user_id,user_description,user_follower_count,user_friends_count,user_verified,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,None,1250294694937915394,Twitter user,14,180,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,None,57059492,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,False,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,None,1016022678,"Wisdom is knowing the right path to take, Inte...",285,1013,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,None,1085818329816883201,Twitter user,147,467,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,None,1227501071490113537,it's not my attitude it's my style,2,24,False,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,None,1168840190426632192,Bhola sa chora,254,513,False,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,None,1696615807,Random person who likes drawing (but not a \nl...,23,754,False,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,None,1313330869113745413,Twitter user,2,2,False,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,None,1161551282995388416,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,False,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,None,1211810532006612992,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,False,i hate talking to people from my department bu...,139

In [56]:
st=df["created_at"].str
st

In [57]:
st[0:4]

0        2020
1        2020
2        2020
3        2020
4        2020
         ...
47376    2020
47377    2020
47378    2020
47379    2020
47380    2020
Name: created_at, Length: 47381, dtype: object

In [58]:
st[5:7]

0        10
1        10
2        10
3        10
4        10
         ..
47376    10
47377    10
47378    10
47379    10
47380    10
Name: created_at, Length: 47381, dtype: object